[project]
name = "ird-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "aiosmtplib>=4.0.1",
    "certifi>=2025.6.15",
    "fastapi[all]>=0.115.14",
    "google-auth>=2.40.3",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.2",
    "passlib[argon2]>=1.7.4",
    "pyjwt>=2.10.1",
    "pymongo[srv]>=4.13.2",
    "redis>=6.2.0",
    "tzlocal>=5.3.1",
]
