name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker images
        run: docker build -t backend:dev .
      - name: Deploy
        run: /home/ubuntu/dev_app/deploy-api.sh
